# SET @MFAID = 35; /* FIAT */
   SELECT MANUFACTURERS.MFA_BRAND,
          get_text(IFNULL(`MS_COUNTRY_SPECIFICS`.`MSCS_NAME_DES`,`MODELS_SERIES`.`MS_NAME_DES`), 16) AS 'MS_NAME',
         `MODELS_SERIES`.`MS_CI_FROM`,
         `MODELS_SERIES`.`MS_CI_TO`
   FROM 
         `MODELS_SERIES`
          LEFT OUTER JOIN `MS_COUNTRY_SPECIFICS`
                       ON `MS_COUNTRY_SPECIFICS`.`MSCS_ID` = `MODELS_SERIES`.`MS_ID`
                      AND `MS_COUNTRY_SPECIFICS`.`MSCS_COU_ID` = 51 
					INNER JOIN MANUFACTURERS ON MANUFACTURERS.MFA_ID = `MODELS_SERIES`.`MS_MFA_ID`
   WHERE  
         `MODELS_SERIES`.`MS_MFA_ID` = 35
          AND`MODELS_SERIES`.`MS_PC` = 1