 SET @PCID = 1014; /* FORD TRANSIT Bus (V_ _) 2.0 (VAS, VIL, VLS, VUL, VZS) */ 

   SELECT
         CONCAT( MFA_BRAND, ' ',  
                 get_text(IFNULL(`MS_COUNTRY_SPECIFICS`.`MSCS_NAME_DES`,`MODELS_SERIES`.`MS_NAME_DES`), @LNGID), ' ', 
                 get_text(PASSENGER_CARS.PC_MODEL_DES, @LNGID) ) AS TYPEL,
         PC_COUNTRY_SPECIFICS.PCS_CONSTRUCTION_INTERVAL_START,
         PC_COUNTRY_SPECIFICS.PCS_CONSTRUCTION_INTERVAL_END,
         PC_COUNTRY_SPECIFICS.PCS_POWER_KW,
         PC_COUNTRY_SPECIFICS.PCS_POWER_PS,
         PC_COUNTRY_SPECIFICS.PCS_CAPACITY_TAX,
         PC_COUNTRY_SPECIFICS.PCS_CAPACITY_LT,
         PC_COUNTRY_SPECIFICS.PCS_CAPACITY_TECH,
         PC_COUNTRY_SPECIFICS.PCS_ABS,
         PC_COUNTRY_SPECIFICS.PCS_ASR,
         PC_COUNTRY_SPECIFICS.PCS_NUMBER_OF_CYLINDERS,
         
         get_text(PC_COUNTRY_SPECIFICS.PCS_BODY_TYPE, @LNGID) AS PC_BODY_TYPE,
		 get_text(PC_COUNTRY_SPECIFICS.PCS_ENGINE_TYPE, @LNGID) AS PC_ENGINE_TYPE,
         get_text(PC_COUNTRY_SPECIFICS.PCS_GEAR_TYPE, @LNGID) AS PC_GEAR_TYPE,
         get_text(PC_COUNTRY_SPECIFICS.PCS_DRIVE_TYPE, @LNGID) AS PC_DRIVE_TYPE,
         get_text(PC_COUNTRY_SPECIFICS.PCS_BRAKE_SYSTEM, @LNGID) AS PC_BRAKE_SYSTEM,
         get_text(PC_COUNTRY_SPECIFICS.PCS_BRAKE_TYPE, @LNGID) AS PC_BRAKE_TYPE,
         get_text(PC_COUNTRY_SPECIFICS.PCS_FUEL_TYPE, @LNGID) AS PC_FUEL_TYPE,
         get_text(PC_COUNTRY_SPECIFICS.PCS_CATALYSATOR_TYPE, @LNGID) AS PC_CATALYSATOR_TYPE,
         get_text(PC_COUNTRY_SPECIFICS.PCS_FUEL_MIXTURE, @LNGID)  AS PC_FUEL_MIXTURE,
         
         (SELECT
                GROUP_CONCAT(ENGINES.ENG_CODE)
          FROM
                ENGINES
                JOIN ENG_DESIGNATIONS ON (ENGINES.ENG_ID=ENG_DESIGNATIONS.ENG_ID)
          WHERE
                ENG_DESIGNATIONS.PC_ID = PASSENGER_CARS.PC_ID) AS PC_ENG_CODES
         
   FROM 
         PASSENGER_CARS
         
         INNER JOIN PC_COUNTRY_SPECIFICS ON PC_COUNTRY_SPECIFICS.PCS_PC_ID = PASSENGER_CARS.PC_ID
              AND (PC_COUNTRY_SPECIFICS.PCS_COU_ID = @COUNTRY_FILTER OR PC_COUNTRY_SPECIFICS.PCS_COU_ID = 0)
         
         INNER JOIN MODELS_SERIES ON MODELS_SERIES.MS_ID = PASSENGER_CARS.PC_MS_ID
         
         INNER JOIN MANUFACTURERS ON MANUFACTURERS.MFA_ID = PASSENGER_CARS.PC_MFA_ID
         
         LEFT OUTER JOIN `MS_COUNTRY_SPECIFICS`
                      ON `MS_COUNTRY_SPECIFICS`.`MSCS_ID` = `MODELS_SERIES`.`MS_ID`
                     AND `MS_COUNTRY_SPECIFICS`.`MSCS_COU_ID` = @COUNTRY_FILTER 

   WHERE 
         PASSENGER_CARS.PC_ID = @PCID