SET @KBA_NUM = '0588549';
   SET @TYPE_NUM_COU_CODE = 'D';
   
   SELECT
         CONCAT( MFA_BRAND, ' ',  
                 get_text(IFNULL(`MS_COUNTRY_SPECIFICS`.`MSCS_NAME_DES`,`MODELS_SERIES`.`MS_NAME_DES`), @LNGID), ' ', 
                 get_text(PASSENGER_CARS.PC_MODEL_DES, @LNGID) ) AS TYPEL,
         PC_COUNTRY_SPECIFICS.PCS_CONSTRUCTION_INTERVAL_START,
         PC_COUNTRY_SPECIFICS.PCS_CONSTRUCTION_INTERVAL_END,
         PC_COUNTRY_SPECIFICS.PCS_POWER_KW,
         PC_COUNTRY_SPECIFICS.PCS_POWER_PS,
         PC_COUNTRY_SPECIFICS.PCS_CAPACITY_TAX,
         get_text(PC_COUNTRY_SPECIFICS.PCS_BODY_TYPE, @LNGID)
   FROM 
         TYPE_NUMBERS
         INNER JOIN PASSENGER_CARS ON PASSENGER_CARS.PC_ID = TYPE_NUMBERS.PC_ID
         
         INNER JOIN PC_COUNTRY_SPECIFICS ON PC_COUNTRY_SPECIFICS.PCS_PC_ID = PASSENGER_CARS.PC_ID
               AND (PC_COUNTRY_SPECIFICS.PCS_COU_ID = @COUNTRY_FILTER OR PC_COUNTRY_SPECIFICS.PCS_COU_ID = 0)
         
         INNER JOIN MODELS_SERIES ON MODELS_SERIES.MS_ID = PASSENGER_CARS.PC_MS_ID
         
         INNER JOIN MANUFACTURERS ON MANUFACTURERS.MFA_ID = PASSENGER_CARS.PC_MFA_ID
         
         LEFT OUTER JOIN MS_COUNTRY_SPECIFICS
                      ON MS_COUNTRY_SPECIFICS.MSCS_ID = MODELS_SERIES.MS_ID
                     AND MS_COUNTRY_SPECIFICS.MSCS_COU_ID = @COUNTRY_FILTER 
	 
   WHERE 
	 TYPE_NUMBERS.TYP_NUM = @KBA_NUM
        AND TYPE_NUMBERS.COU_CODE = @TYPE_NUM_COU_CODE